export default function Head() {
    return (
        <>
            <title>Скупка Антиквариата В Санкт-Петербурге</title>
            <meta charSet="UTF-8" />
            <meta
                name="viewport"
                content="width=device-width, minimal-scale=1, initial-scale=1, maximum-scale=1"
            />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta
                name="description"
                content="Оценка и выкуп антиквариата по фото онлайн в день обращения. Работает профессионал с 30-ти летним опытом. Дорого покупаем раритетные и старинные вещи: посуда, книги, картины, иконы, игрушки, фотографии и многое другое"
            />
            <meta
                name="keywords"
                content="Оценка антиквариата, антиквариат, скупка антиквариата, выкуп антиквариата, антикварный магазин, скупка старинных книг, скупка старинной мебели,скупка старинной посуды,скупка фарфора, скупка советских вещей"
            />
            <link rel="canonical" href="https://spb-antiques.ru" />
        </>
    );
}
